In [25]:
import numpy as np

In [2]:
import tensorflow as tf
print(tf.__version__)

1.5.0


In [3]:
seed=42
np.random.seed(seed)

### sigma * np.random.randn(...) + mu

In [18]:
row1=np.random.randn(1, 5)
print(row1)

[[ 1.46564877 -0.2257763   0.0675282  -1.42474819 -0.54438272]]


In [19]:
row2=np.random.randn(1, 5)
print(row2)

[[ 0.11092259 -1.15099358  0.37569802 -0.60063869 -0.29169375]]


In [21]:
com=np.concatenate((row1, row2), axis=0)
print(com)
print(com.shape)

[[ 1.46564877 -0.2257763   0.0675282  -1.42474819 -0.54438272]
 [ 0.11092259 -1.15099358  0.37569802 -0.60063869 -0.29169375]]
(2, 5)


In [33]:
row0=np.array([[0,0,0,0,0]])

In [36]:
row0.shape

(1, 5)

In [35]:
row0

array([[0, 0, 0, 0, 0]])

In [37]:
row=np.random.randn(1, 5)

In [38]:
com=np.concatenate((row0,row), axis=0)

In [39]:
com

array([[ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.73846658,  0.17136828, -0.11564828, -0.3011037 , -1.47852199]])

In [47]:
row0=np.array([[0,0,0,0,0]])
for _ in range(5):
    row=np.random.randn(1, 5)
    row0=np.concatenate((row0,row), axis=0)
    print(row0)

[[ 0.          0.          0.          0.          0.        ]
 [ 0.82718325  0.01300189  1.45353408 -0.26465683  2.72016917]]
[[ 0.          0.          0.          0.          0.        ]
 [ 0.82718325  0.01300189  1.45353408 -0.26465683  2.72016917]
 [ 0.62566735 -0.85715756 -1.0708925   0.48247242 -0.22346279]]
[[ 0.          0.          0.          0.          0.        ]
 [ 0.82718325  0.01300189  1.45353408 -0.26465683  2.72016917]
 [ 0.62566735 -0.85715756 -1.0708925   0.48247242 -0.22346279]
 [ 0.71400049  0.47323762 -0.07282891 -0.84679372 -1.51484722]]
[[ 0.          0.          0.          0.          0.        ]
 [ 0.82718325  0.01300189  1.45353408 -0.26465683  2.72016917]
 [ 0.62566735 -0.85715756 -1.0708925   0.48247242 -0.22346279]
 [ 0.71400049  0.47323762 -0.07282891 -0.84679372 -1.51484722]
 [-0.44651495  0.85639879  0.21409374 -1.24573878  0.17318093]]
[[ 0.          0.          0.          0.          0.        ]
 [ 0.82718325  0.01300189  1.45353408 -0.26465683  

In [48]:
with open("numpy_out_data", 'w') as f:
    for r in row0:
        f.write(str(r))
        f.write('\n')

In [49]:
row0

array([[ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.82718325,  0.01300189,  1.45353408, -0.26465683,  2.72016917],
       [ 0.62566735, -0.85715756, -1.0708925 ,  0.48247242, -0.22346279],
       [ 0.71400049,  0.47323762, -0.07282891, -0.84679372, -1.51484722],
       [-0.44651495,  0.85639879,  0.21409374, -1.24573878,  0.17318093],
       [ 0.38531738, -0.88385744,  0.15372511,  0.05820872, -1.1429703 ]])

In [50]:
import pandas as pd
df=pd.DataFrame(row0)

In [51]:
df

0         1         2         3         4
0  0.000000  0.000000  0.000000  0.000000  0.000000
1  0.827183  0.013002  1.453534 -0.264657  2.720169
2  0.625667 -0.857158 -1.070892  0.482472 -0.223463
3  0.714000  0.473238 -0.072829 -0.846794 -1.514847
4 -0.446515  0.856399  0.214094 -1.245739  0.173181
5  0.385317 -0.883857  0.153725  0.058209 -1.142970

In [56]:
df.to_csv('data_input_from_numpy.txt',sep=' ',index=False, header=False,float_format='%.3f')