##  Use numpy array and Tensorflow to generate a data set

### we can reshape the one-dim array into two-dim by the reshape method

In [40]:
a1=np.random.rand(1,27)
a2=a1.reshape(3,9)
print(type(a2))
print(a2)
print(a2.ndim)
print(a2.shape)

<class 'numpy.ndarray'>
[[0.30090974 0.66177577 0.2326442  0.82224535 0.78979423 0.00153662
  0.9340471  0.25567293 0.37711603]
 [0.08741331 0.63506048 0.91768136 0.45141664 0.32954384 0.79426063
  0.87688937 0.50462156 0.80824563]
 [0.79503082 0.21400871 0.71030488 0.82862563 0.74212822 0.20940816
  0.7980455  0.98982218 0.36254475]]
2
(3, 9)


In [41]:
row0=[0,1  , 0,0,0   ]
row1=[1,0  , 0,0,0   ]
row2=[0,0  , 1,0,0   ]

ary_2D=np.array([row0,row1,row2])
print(type(ary_2D))
print(ary_2D)
print(ary_2D.dtype)
print(ary_2D.ndim)
print(ary_2D.shape)
print(ary_2D.size)
print(ary_2D[1,1])

<class 'numpy.ndarray'>
[[0 1 0 0 0]
 [1 0 0 0 0]
 [0 0 1 0 0]]
int64
2
(3, 5)
15
0


In [43]:
train=a2,ary_2D

In [44]:
print(type(train))

<class 'tuple'>


In [48]:
train[0]

array([[0.30090974, 0.66177577, 0.2326442 , 0.82224535, 0.78979423,
        0.00153662, 0.9340471 , 0.25567293, 0.37711603],
       [0.08741331, 0.63506048, 0.91768136, 0.45141664, 0.32954384,
        0.79426063, 0.87688937, 0.50462156, 0.80824563],
       [0.79503082, 0.21400871, 0.71030488, 0.82862563, 0.74212822,
        0.20940816, 0.7980455 , 0.98982218, 0.36254475]])

In [49]:
import tensorflow as tf

In [50]:
train_data = tf.data.Dataset.from_tensor_slices(train)

In [51]:
print(train_data.output_types)
print(train_data.output_shapes)

(tf.float64, tf.int64)
(TensorShape([Dimension(9)]), TensorShape([Dimension(5)]))


In [52]:
iterator = tf.data.Iterator.from_structure(train_data.output_types,
                                           train_data.output_shapes)

In [54]:
train_init = iterator.make_initializer(train_data)

In [55]:
img, label = iterator.get_next()

In [61]:
with tf.Session() as sess:
    sess.run(train_init)    # drawing samples from train_data
    print(sess.run([img,label]))
    print(sess.run([img,label]))
    print(sess.run([img,label]))

[array([0.30090974, 0.66177577, 0.2326442 , 0.82224535, 0.78979423,
       0.00153662, 0.9340471 , 0.25567293, 0.37711603]), array([0, 1, 0, 0, 0])]
[array([0.08741331, 0.63506048, 0.91768136, 0.45141664, 0.32954384,
       0.79426063, 0.87688937, 0.50462156, 0.80824563]), array([1, 0, 0, 0, 0])]
[array([0.79503082, 0.21400871, 0.71030488, 0.82862563, 0.74212822,
       0.20940816, 0.7980455 , 0.98982218, 0.36254475]), array([0, 0, 1, 0, 0])]
