## list : Python's most useful built-in type
## A list is a sequence of values
## In a string, the values are characters; in a list, they can be any type

In [3]:
numbers=[11,44,90,0,22.5]
print(numbers)
print(type(numbers))

[11, 44, 90, 0, 22.5]
<class 'list'>


In [1]:
t1=['hello su-yung',999,'great','study hard','do research"']
print(t1)
print(type(t1))

['hello su-yung', 999, 'great', 'study hard', 'do research"']
<class 'list'>


## lists are mutable

In [2]:
t1[0]

'hello su-yung'

In [8]:
t1[1]

999

In [9]:
t1[1]=999999

In [10]:
t1

['hello su-yung', 999999, 'great', 'study hard', 'do research"']

## Traversing a List using for,range

In [3]:
for ch in t1:
    print(ch)

hello su-yung
999
great
study hard
do research"


In [7]:
lengt=len(t1)
print(lengt)

5


In [6]:
for i in range(2,7):
    print(i)

2
3
4
5
6


In [8]:
for i in range(7):
    print(i)

0
1
2
3
4
5
6


In [20]:
for i in range(lengt):
    print(i)
    print(t1[i])
    print('----')

0
hello su-yung
----
1
999999
----
2
great
----
3
study hard
----
4
do research"
----


## list operation

In [21]:
a=[1,2,3]
b=[4,5,6]
c=a+b
print(c)

[1, 2, 3, 4, 5, 6]


In [22]:
a*3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

## list slices

In [18]:
t=['a','bb','cc',99,'55','life is hard']

In [19]:
t[0]

'a'

In [20]:
99 in t

True

In [21]:
length=len(t)
print(length)
print(t[5])

6
life is hard


In [22]:
t[1:3]

['bb', 'cc']

In [23]:
t[:3]

['a', 'bb', 'cc']

In [24]:
em=t[3:3]
print(em)

[]


In [25]:
print(type(em))

<class 'list'>


## list method: append modified the list and returns None

In [26]:
t1=[1,2,'a']
t2=t1.append(3)
print('t1=',t1)
print('t2=',t2)
t1.append('Go')
print('t1=',t1)

t1= [1, 2, 'a', 3]
t2= None
t1= [1, 2, 'a', 3, 'Go']


## ndarray

In [1]:
import numpy as np

## create a one-dim array

In [2]:
my_first_matrix=np.array([3,4,5,6])

In [3]:
print(my_first_matrix)
print(type(my_first_matrix))

[3 4 5 6]
<class 'numpy.ndarray'>


In [4]:
my_second_matrix=np.array([[3,4,5],[2,3,4],[4,5,6]])
print(my_second_matrix)
print(type(my_second_matrix))

[[3 4 5]
 [2 3 4]
 [4 5 6]]
<class 'numpy.ndarray'>


## create dataframe

In [6]:
import pandas as pd

In [13]:
te=np.array([[3.4,4.6,5.2],[2.1,3.2,4.9],[4.2,5.2,6.6]])
print(te)

[[ 3.4  4.6  5.2]
 [ 2.1  3.2  4.9]
 [ 4.2  5.2  6.6]]


In [14]:
df=pd.DataFrame(te,index=['aa','bb','cc'],columns=[0,1,2])

In [15]:
df

0    1    2
aa  3.4  4.6  5.2
bb  2.1  3.2  4.9
cc  4.2  5.2  6.6

In [19]:
df=pd.DataFrame(te,index=['aa','bb','cc'],columns=['A','B','C'])

In [20]:
df

A    B    C
aa  3.4  4.6  5.2
bb  2.1  3.2  4.9
cc  4.2  5.2  6.6

In [21]:
df["A"]

aa    3.4
bb    2.1
cc    4.2
Name: A, dtype: float64

In [24]:
print(type(df["A"]))

<class 'pandas.core.series.Series'>


In [22]:
df["A"]/1.5

aa    2.266667
bb    1.400000
cc    2.800000
Name: A, dtype: float64

In [25]:
x=np.ceil(df["A"]/1.5)

In [33]:
x

aa    100.0
bb      2.0
cc    100.0
Name: A, dtype: float64

In [34]:
x.where(x<3,100,inplace=False)

aa    100.0
bb      2.0
cc    100.0
Name: A, dtype: float64

In [35]:
x

aa    100.0
bb      2.0
cc    100.0
Name: A, dtype: float64