# To use Series, DataFrame,,,, import pandas 
# To use array, import numpy

In [1]:
import pandas as pd
import numpy as np

## t1 is a list.   list -> array
## a1 is a NumPy array

In [2]:
t1=[100,22,434,556]
a1=np.array(t1)
print(t1)
print(a1)

[100, 22, 434, 556]
[100  22 434 556]


## create a Series from list
## list -> series

In [3]:
data_1=pd.Series(t1)
print(data_1)

0    100
1     22
2    434
3    556
dtype: int64


## create a Series from array
## array -> series

In [5]:
data_2=pd.Series(a1)
print(data_1)

0    100
1     22
2    434
3    556
dtype: int64


## the index of series need not be an integer

In [6]:
data_3=pd.Series(t1,index=['a','b','c','d'])
print(data_3)

a    100
b     22
c    434
d    556
dtype: int64


In [16]:
dd=pd.DataFrame()

In [18]:
se1=pd.Series({"x":1,"y":2},name="a")
print(se1)

x    1
y    2
Name: a, dtype: int64


In [19]:
dd.append(se1)

/tmp/ipykernel_7169/1948028963.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  dd.append(se1)


x  y
a  1  2

## Creat a student grade series
## we have students : 'John','Mary', 'susan', 'Peter', 'Lin'

In [4]:
students=['John','Mary','susan','Peter','Lin']
Grade=[90,60,70,100,95]
data_4 = pd.Series(Grade,index=students)
print(data_4)
print(type(data_4))
print(data_4[0])
print(data_4[3])
print(data_4['susan'])

John      90
Mary      60
susan     70
Peter    100
Lin       95
dtype: int64
<class 'pandas.core.series.Series'>
90
100
70


## series values can be list

In [8]:
t2=[[1,2,3],[2,3,4],[4,5,6],[0,2,4.5],['go','go','never give up']]
data_5=pd.Series(t2)
print(data_5)

0                  [1, 2, 3]
1                  [2, 3, 4]
2                  [4, 5, 6]
3                [0, 2, 4.5]
4    [go, go, never give up]
dtype: object


## can we iterate a Series ? 

In [9]:
for item in t2:
    print(item)

[1, 2, 3]
[2, 3, 4]
[4, 5, 6]
[0, 2, 4.5]
['go', 'go', 'never give up']


## how to index a Series ?

In [13]:
print(data_4)
print(data_4[0])

John      90
Mary      60
susan     70
Peter    100
Lin       95
dtype: int64
90


In [14]:
# the series value is int
print(type(data_4[0]))

<class 'numpy.int64'>


In [15]:
data_4[3]

100

In [16]:
data_4[0:2]

John    90
Mary    60
dtype: int64

In [17]:
data_4['susan']

70

## can we iterate a Series ?

In [18]:
for item in data_4:
    print(item)

90
60
70
100
95


## Create DataFrame from Series

In [5]:
students=['John','Mary','susan','Peter','Lin']
Grade=[90,60,70,100,95]
midterm_series = pd.Series(Grade,index=students)

In [6]:
hk1=['A','B','A','C','A']
hk1_series=pd.Series(hk1,students)

In [7]:
docid=['22','23','44','55','66']
docid_seres=pd.Series(docid,students)

In [8]:
hk2=['A','A','A','B','A']
hk2_series=pd.Series(hk2,students)

In [9]:
pd1=pd.DataFrame({'Midterm':midterm_series, 'Hk1':hk1_series,
                 'HK2':hk2_series,'docid':docid_seres})

In [15]:
print(pd1)

       Midterm Hk1 HK2 docid
John        90   A   A    22
Mary        60   B   A    23
susan       70   A   A    44
Peter      100   C   B    55
Lin         95   A   A    66


In [10]:
students1=['John','Peter','Lin']
chem=[9,0,7]
chem_series = pd.Series(chem,index=students1)

docid=['22','44','66']
docid_seres=pd.Series(docid,students1)

pd2=pd.DataFrame({'chem':chem_series, 'docid':docid_seres  })

In [11]:
pd1

Midterm Hk1 HK2 docid
John        90   A   A    22
Mary        60   B   A    23
susan       70   A   A    44
Peter      100   C   B    55
Lin         95   A   A    66

In [12]:
pd2

chem docid
John      9    22
Peter     0    44
Lin       7    66

In [20]:
students1=['helen']
chem=[33]
chem_series = pd.Series(chem,index=students1)

docid=['44']
docid_seres=pd.Series(docid,students1)

pd3=pd.DataFrame({'chem':chem_series, 'docid':docid_seres  })

In [21]:
pd3

chem docid
helen    33    44

## Merge two dataframe

In [27]:
mm=pd.merge(pd1,pd2,on='docid')
print(mm)

   Midterm Hk1 HK2 docid  chem
0       90   A   A    22     9
1       70   A   A    44     0
2       95   A   A    66     7


## concat two dataframe

In [28]:
cc=pd.concat([mm,pd3])
print(cc)

       Midterm  Hk1  HK2 docid  chem
0         90.0    A    A    22     9
1         70.0    A    A    44     0
2         95.0    A    A    66     7
helen      NaN  NaN  NaN    44    33


## how to remove NA rows

## how to remove duplicate docid

In [30]:
cc['docid'].duplicated()

0        False
1        False
2        False
helen     True
Name: docid, dtype: bool

In [32]:
cc.drop_duplicates(subset=['docid'],keep='first')

Midterm Hk1 HK2 docid  chem
0     90.0   A   A    22     9
1     70.0   A   A    44     0
2     95.0   A   A    66     7

In [10]:
chem_series

John     9
Peter    0
Lin      7
dtype: int64

## how to select a DataFrame?

In [24]:
# first three rows
pd1[:3]

Midterm Hk1 HK2
John        90   A   A
Mary        60   B   A
susan       70   A   A

In [25]:
# first three rows
pd1[0:3]

Midterm Hk1 HK2
John        90   A   A
Mary        60   B   A
susan       70   A   A

In [32]:
# first three rows
pd1['John':'susan']

Midterm Hk1 HK2
John        90   A   A
Mary        60   B   A
susan       70   A   A

## first three rows

In [26]:
pd1.iloc[:3,:]

Midterm Hk1 HK2
John        90   A   A
Mary        60   B   A
susan       70   A   A

## first three rows,  將index 放入 list 

In [27]:
index=['John','Mary','susan']
pd1.loc[index]

Midterm Hk1 HK2
John        90   A   A
Mary        60   B   A
susan       70   A   A

In [28]:
index=['John','Mary','Lin']
pd1.loc[index]

Midterm Hk1 HK2
John       90   A   A
Mary       60   B   A
Lin        95   A   A

# 取欄位 ,   用 .loc

In [29]:
pd1.loc[:,:'Hk1']

Midterm Hk1
John        90   A
Mary        60   B
susan       70   A
Peter      100   C
Lin         95   A

## 取欄位 , 用 .iloc

In [30]:
pd1.iloc[:,:2]

Midterm Hk1
John        90   A
Mary        60   B
susan       70   A
Peter      100   C
Lin         95   A

In [31]:
pd1[['Midterm',"Hk1"]]

Midterm Hk1
John        90   A
Mary        60   B
susan       70   A
Peter      100   C
Lin         95   A

In [33]:
# first two rows, two cols
pd1.iloc[:2,:2]

Midterm Hk1
John       90   A
Mary       60   B

In [34]:
pd1.loc[:'Mary',:'Hk1']

Midterm Hk1
John       90   A
Mary       60   B

In [48]:
pd1.loc['John','Hk1']

'A'

In [35]:
pd1.iloc[0,2]

'A'

In [36]:
# take a colum
col=pd1['Hk1']
print(col)

John     A
Mary     B
susan    A
Peter    C
Lin      A
Name: Hk1, dtype: object


In [37]:
print(type(col))

<class 'pandas.core.series.Series'>


In [38]:
# take two columns
cols=pd1[['Hk1','HK2']]
print(cols)

      Hk1 HK2
John    A   A
Mary    B   A
susan   A   A
Peter   C   B
Lin     A   A


In [52]:
print(type(cols))

<class 'pandas.core.frame.DataFrame'>


In [53]:
pd1[['Hk1']]

Hk1
John    A
Mary    B
susan   A
Peter   C
Lin     A

## Create a DataFrame from 2-D array

In [54]:
ary=np.array([ [1,2,3],[4,5,6],[7,8,9],[2,2,2],[6,6,6],[7,7,7]])
print(ary)
print(ary.shape)
print(type(ary))

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [2 2 2]
 [6 6 6]
 [7 7 7]]
(6, 3)
<class 'numpy.ndarray'>


In [55]:
df_test=pd.DataFrame(ary,columns=['col0','col1','col3'])
print(df_test)

   col0  col1  col3
0     1     2     3
1     4     5     6
2     7     8     9
3     2     2     2
4     6     6     6
5     7     7     7


## add a column

In [56]:
df_test['key1']=['A','S','B','A','A','B']

In [57]:
print(df_test)

   col0  col1  col3 key1
0     1     2     3    A
1     4     5     6    S
2     7     8     9    B
3     2     2     2    A
4     6     6     6    A
5     7     7     7    B


## Create a DatataFrame from a list of dicts

In [65]:
dfmm=pd.DataFrame( [ {'key':'A','data':1} , 
                     {'key':'B','data':2} ,
                     {'key':'C','data':3} ,                       
                     {'key':'A','data':4} ,
                     {'key':'B', 'data':5},
                     {'key':'C','data':6}
                   ]  
                 )


In [66]:
print(dfmm)

   data key
0     1   A
1     2   B
2     3   C
3     4   A
4     5   B
5     6   C
