## list : Python's most useful built-in type
## A list is a sequence of values
## In a string, the values are characters; in a list, they can be any type

In [1]:
numbers=[11,44,90,0,22.5]
print(numbers)
print(type(numbers))

[11, 44, 90, 0, 22.5]
<class 'list'>


In [2]:
t1=['hello su-yung',999,'great','study hard','do research"']
print(t1)
print(type(t1))

['hello su-yung', 999, 'great', 'study hard', 'do research"']
<class 'list'>


## lists are mutable

In [3]:
t1[0]

'hello su-yung'

In [4]:
t1[1]

999

In [5]:
t1[1]=999999

In [6]:
t1

['hello su-yung', 999999, 'great', 'study hard', 'do research"']

## Traversing a List using for,range

In [7]:
for ch in t1:
    print(ch)

hello su-yung
999999
great
study hard
do research"


In [8]:
lengt=len(t1)
print(lengt)

5


In [9]:
for i in range(2,7):
    print(i)

2
3
4
5
6


In [10]:
for i in range(7):
    print(i)

0
1
2
3
4
5
6


In [11]:
for i in range(lengt):
    print(i)
    print(t1[i])
    print('----')

0
hello su-yung
----
1
999999
----
2
great
----
3
study hard
----
4
do research"
----


## list operation

In [12]:
a=[1,2,3]
b=[4,5,6]
c=a+b
print(c)

[1, 2, 3, 4, 5, 6]


In [13]:
a*3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

##  limitation of list

In [14]:
a-0.2

TypeError: unsupported operand type(s) for -: 'list' and 'float'

In [15]:
a-2

TypeError: unsupported operand type(s) for -: 'list' and 'int'

## list slices

In [16]:
t=['a','bb','cc',99,'55','life is hard']

In [17]:
t[0]

'a'

In [18]:
99 in t

True

In [19]:
length=len(t)
print(length)
print(t[5])

6
life is hard


In [20]:
t[1:3]

['bb', 'cc']

In [21]:
t[:3]

['a', 'bb', 'cc']

In [22]:
em=t[3:3]
print(em)

[]


In [23]:
print(type(em))

<class 'list'>


## list method: append modified the list and returns None

In [24]:
t1=[1,2,'a']
t2=t1.append(3)
print('t1=',t1)
print('t2=',t2)
t1.append('Go')
print('t1=',t1)

t1= [1, 2, 'a', 3]
t2= None
t1= [1, 2, 'a', 3, 'Go']


## Why use ndarray instead of list ?
##  Arrays are fast, and memory efficent than list 

## ndarray

In [25]:
# to use ndarray, do not forget to import numpy
import numpy as np

### create a one-dim array from list
### type : ndarray
### shape : (4,) 
### size: 4

In [26]:
my_first_array=np.array([3,4,5,6])

### ndim, shape,  size 

In [31]:
print(my_first_array)
print(type(my_first_array))
print(my_first_array.ndim)
print(my_first_array.shape)
print(my_first_array.size)

[3 4 5 6]
<class 'numpy.ndarray'>
1
(4,)
4


In [32]:
my_first_array_tran=my_first_array.transpose()
print(my_first_array_tran)
print(my_first_array_tran.ndim)
print(my_first_array_tran.shape)

[3 4 5 6]
1
(4,)


In [52]:
my_array=np.array([[3],[4],[5],[6]])
print(my_array)
print(type(my_array))
print(my_array.ndim)
print(my_array.shape)
print(my_array.size)
print(my_array.transpose())

[[3]
 [4]
 [5]
 [6]]
<class 'numpy.ndarray'>
2
(4, 1)
4
[[3 4 5 6]]


In [57]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
sc.fit(my_array)
print(sc.mean_)

[ 4.5]


/home/how/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


### how about scalar ? 

In [33]:
my_scalar=np.array([3])

In [34]:
print(my_scalar)
print(type(my_scalar))
print(my_scalar.ndim)
print(my_scalar.shape)
print(my_scalar)

[3]
<class 'numpy.ndarray'>
1
(1,)
[3]


In [35]:
my_scalar=np.array(7)

In [36]:
print(my_scalar)
print(type(my_scalar))
print(my_scalar.ndim)
print(my_scalar.shape)
print(my_scalar)

7
<class 'numpy.ndarray'>
0
()
7


## apply a calculation to each element
## note : not for list ! 

In [37]:
my_first_array-0.2

array([ 2.8,  3.8,  4.8,  5.8])

In [38]:
my_first_array*2

array([ 6,  8, 10, 12])

In [39]:
my_first_array**2

array([ 9, 16, 25, 36])

## 三角函數 :　 sin (3.1416 radian )=sin(180 degree)=0 
## sin(3 radian) = 0.141

In [40]:
import math
print(my_first_array)
print('math.pi=',math.pi)
my_first_array_test=np.append(my_first_array  ,  math.pi)
print(my_first_array_test)
print(np.sin(my_first_array_test)) 

[3 4 5 6]
math.pi= 3.141592653589793
[ 3.          4.          5.          6.          3.14159265]
[  1.41120008e-01  -7.56802495e-01  -9.58924275e-01  -2.79415498e-01
   1.22464680e-16]


## a review of numpy array 

In [41]:
t=np.linspace(0, math.pi, num=5)
print(t)
print(np.sin(t))
print(np.cos(t)+0.1)
print(type(np.sin(t)))
print(2*np.sin(t))
print(2*np.sin(t)-3)
print((2*np.sin(t)-3  )    / (np.cos(t)+0.1))

[ 0.          0.78539816  1.57079633  2.35619449  3.14159265]
[  0.00000000e+00   7.07106781e-01   1.00000000e+00   7.07106781e-01
   1.22464680e-16]
[ 1.1         0.80710678  0.1        -0.60710678 -0.9       ]
<class 'numpy.ndarray'>
[  0.00000000e+00   1.41421356e+00   2.00000000e+00   1.41421356e+00
   2.44929360e-16]
[-3.         -1.58578644 -1.         -1.58578644 -3.        ]
[-2.72727273 -1.96477898 -10.          2.61203875  3.33333333]


## 2D array

In [42]:
my_second_array=np.array([[3,4,5,2],[2,3,4,6],[4,5,6,1]])
print(my_second_array)
print(type(my_second_array))
print(my_second_array.shape)
print(my_second_array.ndim)
print(my_second_array.size)

[[3 4 5 2]
 [2 3 4 6]
 [4 5 6 1]]
<class 'numpy.ndarray'>
(3, 4)
2
12


In [44]:
my_second_array_t=my_second_array.transpose()
print(my_second_array_t)

[[3 2 4]
 [4 3 5]
 [5 4 6]
 [2 6 1]]


## lets try one more 2-D array

In [45]:
row0=[5.2, 3.0, 4.5]
row1=[9.1 ,0.1 ,0.3]

ary_2D=np.array([row0,row1])
print(ary_2D)
print(ary_2D.dtype)
print(ary_2D.ndim)
print(ary_2D.shape)
print(ary_2D.size)
print(ary_2D[1,1])

[[ 5.2  3.   4.5]
 [ 9.1  0.1  0.3]]
float64
2
(2, 3)
6
0.1


## creating array from scratch

In [ ]:
## similar to the builtin  range() function
np.arange(5)

In [ ]:
# create a length-5 integer array filled with zero
np.zeros(5)

In [ ]:
#create a length-5 integer array filled with 1
np.ones(5)

In [ ]:
g1=np.arange(1,11)
print(g1)

### np.random.rand
### Random values in a given shape.
### Create an array of the given shape 
### and populate it with random samples from a uniform distribution over [0, 1).


In [ ]:
X=2*np.random.rand(100,1)
print(X.shape)
y=4+3*X+np.random.randn(100,1)
print(y.shape)

In [ ]:
X_b = np.c_[np.ones((100,1)), X]

In [ ]:
X_b

In [ ]:
np.r_['-1,2,0',np.ones((100,1)),X]

In [ ]:
np.c_[np.ones((100,1)), X] == X_b

## we can reshape the one-dim array into two-dim by the reshape method

In [ ]:
g2=g1.reshape((5,2))
print(g2)

In [ ]:
#create a 100x1  array filled with 1
np.ones((100,1))

In [ ]:
#create a 2x4  array filled with 1
np.ones((2,4))

In [ ]:
# create an array of the given shape and populate it with random samples from uniform distribution
np.random.rand(3,2)

## array index

In [ ]:
my_first_array=np.array([3,4,5,6])
print(my_first_array)

In [ ]:
my_first_array

In [ ]:
my_first_array[0]

In [ ]:
print(type(my_first_array[0]))

In [ ]:
my_first_array[3]

In [ ]:
my_first_array[1:3]

In [ ]:
print(type(my_first_array[1:3]))

## for a two-dim array

In [ ]:
my_second_array=np.array([[3,4,5,2],[2,3,4,6],[9,5,6,1]])
print(my_second_array)

In [9]:
ay=np.array([[1,2,3]])
print(ay)
print(ay.shape)
print(ay.ndim)

[[1 2 3]]
(1, 3)
2


In [10]:
ay.T

array([[1],
       [2],
       [3]])

In [12]:
print(ay.T.shape)
print(ay.T.ndim)

(3, 1)
2


In [ ]:
ay=np.array([[1], [2]])
print(ay)
print(ay.shape)
print(ay.ndim)

In [ ]:
ay=np.array([[[1], [2]]])
print(ay)
print(ay.shape)
print(ay.ndim)

In [70]:
np.r_['0,2,-1',[1,2,3],[4,5,6]]

array([[1, 2, 3],
       [4, 5, 6]])

In [71]:
np.r_['0,2,0',[1,2,3],[4,5,6]]

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [69]:
np.r_['-1,2,-1',[1,2,3],[4,5,6]]

array([[1, 2, 3, 4, 5, 6]])

In [68]:
np.r_['-1,2,0',[1,2,3],[4,5,6]]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
my_second_array[0]

In [ ]:
my_second_array[2]

In [ ]:
my_second_array[2,0]

In [ ]:
my_second_array[2,3]

## array slicing: accessing subarray
## x[start:stop:step]

In [ ]:
x=np.arange(11)
print(x)

In [ ]:
print(type(x))

In [ ]:
x[0]

In [ ]:
x[3]

In [ ]:
x[1:10:2]

In [ ]:
x2=np.array( [  [3,4,5,2] , [2,3,4,6] , [9,5,6,1] ] )
print(x2)

In [ ]:
print(x2[0:2,0:2])

## take all rows, 0-1 columns

In [ ]:
x2[:,0:2]

In [ ]:
x2[:,0]

In [ ]:
x2[:,1]

In [ ]:
x2[:,0:1]

## all rows, 3rd column

In [ ]:
x2[:,3]

## all rows, 3rd column, note difference with the above

In [ ]:
x2[:,3:]

In [ ]:
te=np.array([[3.4,4.6,5.2],[2.1,3.2,4.9],[4.2,5.2,6.6]])
print(te)

In [ ]:
te[2,1]

In [ ]:
print(te[0:2])

In [ ]:
print(te[0:2,0:1])

In [ ]:
tet=te[:,2:3]
print(tet)

In [ ]:
print(type(tet))
print(tet.ndim)