## list : Python's most useful built-in type
## A list is a sequence of values
## In a string, the values are characters; in a list, they can be any type

In [ ]:
numbers=[11,44,90,0,22.5]
print(numbers)
print(type(numbers))

In [ ]:
t1=['hello su-yung',999,'great','study hard','do research"']
print(t1)
print(type(t1))

## lists are mutable

In [ ]:
t1[0]

In [ ]:
t1[1]

In [ ]:
t1[1]=999999

In [ ]:
t1

## Traversing a List using for,range

In [ ]:
for ch in t1:
    print(ch)

In [ ]:
lengt=len(t1)
print(lengt)

In [ ]:
for i in range(2,7):
    print(i)

In [ ]:
for i in range(7):
    print(i)

In [ ]:
for i in range(lengt):
    print(i)
    print(t1[i])
    print('----')

## list operation

In [ ]:
a=[1,2,3]
b=[4,5,6]
c=a+b
print(c)

In [ ]:
a*3

##  limitation of list

In [ ]:
a-0.2

In [ ]:
a-2

## list slices

In [ ]:
t=['a','bb','cc',99,'55','life is hard']

In [ ]:
t[0]

In [ ]:
99 in t

In [ ]:
length=len(t)
print(length)
print(t[5])

In [ ]:
t[1:3]

In [ ]:
t[:3]

In [ ]:
em=t[3:3]
print(em)

In [ ]:
print(type(em))

## list method: append modified the list and returns None

In [ ]:
t1=[1,2,'a']
t2=t1.append(3)
print('t1=',t1)
print('t2=',t2)
t1.append('Go')
print('t1=',t1)

## Why use ndarray instead of list ?
##  Arrays are fast, and memory efficent than list 

## ndarray

In [1]:
# to use ndarray, do not forget to import numpy
import numpy as np

### create a one-dim array from list
### type : ndarray
### shape : (4,) 
### size: 4

In [2]:
my_first_array=np.array([3,4,5,6])

### ndim, shape,  size 

In [4]:
print(my_first_array)
print(type(my_first_array))
print(my_first_array.ndim)
print(my_first_array.shape)
print(my_first_array.size)

[3 4 5 6]
<class 'numpy.ndarray'>
1
(4,)
4


### how about scalar ? 

In [5]:
my_scalar=np.array([3])

In [6]:
print(my_scalar)
print(type(my_scalar))
print(my_scalar.ndim)
print(my_scalar.shape)
print(my_scalar)

[3]
<class 'numpy.ndarray'>
1
(1,)
[3]


In [7]:
my_scalar=np.array(7)

In [8]:
print(my_scalar)
print(type(my_scalar))
print(my_scalar.ndim)
print(my_scalar.shape)
print(my_scalar)

7
<class 'numpy.ndarray'>
0
()
7


## apply a calculation to each element
## note : not for list ! 

In [ ]:
my_first_array-0.2

In [ ]:
my_first_array*2

In [ ]:
my_first_array**2

## 三角函數 :　 sin (3.1416 radian )=sin(180 degree)=0 
## sin(3 radian) = 0.141

In [ ]:
import math
print(my_first_array)
print('math.pi=',math.pi)
my_first_array_test=np.append(my_first_array  ,  math.pi)
print(my_first_array_test)
print(np.sin(my_first_array_test)) 

## a review of numpy array 

In [ ]:
t=np.linspace(0, math.pi, num=5)
print(t)
print(np.sin(t))
print(np.cos(t)+0.1)
print(type(np.sin(t)))
print(2*np.sin(t))
print(2*np.sin(t)-3)
print((2*np.sin(t)-3  )    / (np.cos(t)+0.1))

## 2D array

In [ ]:
my_second_array=np.array([[3,4,5,2],[2,3,4,6],[4,5,6,1]])
print(my_second_array)
print(type(my_second_array))
print(my_second_array.shape)
print(my_second_array.ndim)
print(my_second_array.size)

## lets try one more 2-D array

In [ ]:
row0=[5.2, 3.0, 4.5]
row1=[9.1 ,0.1 ,0.3]

ary_2D=np.array([row0,row1])
print(ary_2D)
print(ary_2D.dtype)
print(ary_2D.ndim)
print(ary_2D.shape)
print(ary_2D.size)
print(ary_2D[1,1])

## creating array from scratch

In [ ]:
## similar to the builtin  range() function
np.arange(5)

In [ ]:
# create a length-5 integer array filled with zero
np.zeros(5)

In [ ]:
#create a length-5 integer array filled with 1
np.ones(5)

In [ ]:
g1=np.arange(1,11)
print(g1)

### np.random.rand
### Random values in a given shape.
### Create an array of the given shape 
### and populate it with random samples from a uniform distribution over [0, 1).


In [ ]:
X=2*np.random.rand(100,1)
print(X.shape)
y=4+3*X+np.random.randn(100,1)
print(y.shape)

In [ ]:
X_b = np.c_[np.ones((100,1)), X]

In [ ]:
X_b

In [ ]:
np.r_['-1,2,0',np.ones((100,1)),X]

In [ ]:
np.c_[np.ones((100,1)), X] == X_b

## we can reshape the one-dim array into two-dim by the reshape method

In [ ]:
g2=g1.reshape((5,2))
print(g2)

In [ ]:
#create a 100x1  array filled with 1
np.ones((100,1))

In [ ]:
#create a 2x4  array filled with 1
np.ones((2,4))

In [ ]:
# create an array of the given shape and populate it with random samples from uniform distribution
np.random.rand(3,2)

## array index

In [ ]:
my_first_array=np.array([3,4,5,6])
print(my_first_array)

In [ ]:
my_first_array

In [ ]:
my_first_array[0]

In [ ]:
print(type(my_first_array[0]))

In [ ]:
my_first_array[3]

In [ ]:
my_first_array[1:3]

In [ ]:
print(type(my_first_array[1:3]))

## for a two-dim array

In [ ]:
my_second_array=np.array([[3,4,5,2],[2,3,4,6],[9,5,6,1]])
print(my_second_array)

In [9]:
ay=np.array([[1,2,3]])
print(ay)
print(ay.shape)
print(ay.ndim)

[[1 2 3]]
(1, 3)
2


In [10]:
ay.T

array([[1],
       [2],
       [3]])

In [12]:
print(ay.T.shape)
print(ay.T.ndim)

(3, 1)
2


In [ ]:
ay=np.array([[1], [2]])
print(ay)
print(ay.shape)
print(ay.ndim)

In [ ]:
ay=np.array([[[1], [2]]])
print(ay)
print(ay.shape)
print(ay.ndim)

In [70]:
np.r_['0,2,-1',[1,2,3],[4,5,6]]

array([[1, 2, 3],
       [4, 5, 6]])

In [71]:
np.r_['0,2,0',[1,2,3],[4,5,6]]

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [69]:
np.r_['-1,2,-1',[1,2,3],[4,5,6]]

array([[1, 2, 3, 4, 5, 6]])

In [68]:
np.r_['-1,2,0',[1,2,3],[4,5,6]]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
my_second_array[0]

In [ ]:
my_second_array[2]

In [ ]:
my_second_array[2,0]

In [ ]:
my_second_array[2,3]

## array slicing: accessing subarray
## x[start:stop:step]

In [ ]:
x=np.arange(11)
print(x)

In [ ]:
print(type(x))

In [ ]:
x[0]

In [ ]:
x[3]

In [ ]:
x[1:10:2]

In [ ]:
x2=np.array( [  [3,4,5,2] , [2,3,4,6] , [9,5,6,1] ] )
print(x2)

In [ ]:
print(x2[0:2,0:2])

## take all rows, 0-1 columns

In [ ]:
x2[:,0:2]

In [ ]:
x2[:,0]

In [ ]:
x2[:,1]

In [ ]:
x2[:,0:1]

## all rows, 3rd column

In [ ]:
x2[:,3]

## all rows, 3rd column, note difference with the above

In [ ]:
x2[:,3:]

In [ ]:
te=np.array([[3.4,4.6,5.2],[2.1,3.2,4.9],[4.2,5.2,6.6]])
print(te)

In [ ]:
te[2,1]

In [ ]:
print(te[0:2])

In [ ]:
print(te[0:2,0:1])

In [ ]:
tet=te[:,2:3]
print(tet)

In [ ]:
print(type(tet))
print(tet.ndim)