## list : Python's most useful built-in type
## A list is a sequence of values
## In a string, the values are characters; in a list, they can be any type

In [3]:
numbers=[11,44,90,0,22.5]
print(numbers)
print(type(numbers))

[11, 44, 90, 0, 22.5]
<class 'list'>


In [1]:
t1=['hello su-yung',999,'great','study hard','do research"']
print(t1)
print(type(t1))

['hello su-yung', 999, 'great', 'study hard', 'do research"']
<class 'list'>


## lists are mutable

In [2]:
t1[0]

'hello su-yung'

In [8]:
t1[1]

999

In [9]:
t1[1]=999999

In [10]:
t1

['hello su-yung', 999999, 'great', 'study hard', 'do research"']

## Traversing a List using for,range

In [3]:
for ch in t1:
    print(ch)

hello su-yung
999
great
study hard
do research"


In [7]:
lengt=len(t1)
print(lengt)

5


In [6]:
for i in range(2,7):
    print(i)

2
3
4
5
6


In [8]:
for i in range(7):
    print(i)

0
1
2
3
4
5
6


In [20]:
for i in range(lengt):
    print(i)
    print(t1[i])
    print('----')

0
hello su-yung
----
1
999999
----
2
great
----
3
study hard
----
4
do research"
----


## list operation

In [1]:
a=[1,2,3]
b=[4,5,6]
c=a+b
print(c)

[1, 2, 3, 4, 5, 6]


In [2]:
a*3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [3]:
a-0.2

TypeError: unsupported operand type(s) for -: 'list' and 'float'

## list slices

In [18]:
t=['a','bb','cc',99,'55','life is hard']

In [19]:
t[0]

'a'

In [20]:
99 in t

True

In [21]:
length=len(t)
print(length)
print(t[5])

6
life is hard


In [22]:
t[1:3]

['bb', 'cc']

In [23]:
t[:3]

['a', 'bb', 'cc']

In [24]:
em=t[3:3]
print(em)

[]


In [25]:
print(type(em))

<class 'list'>


## list method: append modified the list and returns None

In [26]:
t1=[1,2,'a']
t2=t1.append(3)
print('t1=',t1)
print('t2=',t2)
t1.append('Go')
print('t1=',t1)

t1= [1, 2, 'a', 3]
t2= None
t1= [1, 2, 'a', 3, 'Go']


## Why use ndarray instead of list ?
##  Arrays are fast, and memory efficent than list 

## ndarray

In [1]:
# to use ndarray, do not forget to import numpy
import numpy as np

## create a one-dim array from list

In [3]:
my_first_array=np.array([3,4,5,6])

In [4]:
print(my_first_array)
print(type(my_first_array))
print(my_first_array.ndim)
print(my_first_array.shape)
print(my_first_array.size)

[3 4 5 6]
<class 'numpy.ndarray'>
1
(4,)
4


## apply a calculation to each element
## note : not for list ! 

In [5]:
my_first_array-0.2

array([ 2.8,  3.8,  4.8,  5.8])

In [10]:
my_first_array*2

array([ 6,  8, 10, 12])

## 2D array

In [10]:
my_second_array=np.array([[3,4,5,2],[2,3,4,6],[4,5,6,1]])
print(my_second_array)
print(type(my_second_array))
print(my_second_array.shape)
print(my_second_array.ndim)
print(my_second_array.size)

[[3 4 5 2]
 [2 3 4 6]
 [4 5 6 1]]
<class 'numpy.ndarray'>
(3, 4)
2
12


## lets try one more 2-D array

In [10]:
row1=[5.2, 3.0, 4.5]
row2=[9.1 ,0.1 ,0.3]

ary_2D=np.array([row1,row2])
print(ary_2D)
print(ary_2D.dtype)
print(ary_2D.ndim)
print(ary_2D.shape)
print(ary_2D.size)
print(ary_2D[1,1])

[[ 5.2  3.   4.5]
 [ 9.1  0.1  0.3]]
float64
2
(2, 3)
6
0.1


## creating array from scratch

In [5]:
## similar to the builtin  range() function
np.arange(5)

array([0, 1, 2, 3, 4])

In [13]:
# create a length-5 integer array filled with zero
np.zeros(5)

array([ 0.,  0.,  0.,  0.,  0.])

In [14]:
#create a length-5 integer array filled with 1
np.ones(5)

array([ 1.,  1.,  1.,  1.,  1.])

In [6]:
g1=np.arange(1,11)
print(g1)

[ 1  2  3  4  5  6  7  8  9 10]


## we can reshape the one-dim array into two-dim by the reshape method

In [8]:
g2=g1.reshape((5,2))
print(g2)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [15]:
#create a 2x4  array filled with 1
np.ones((2,4))

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [18]:
# create an array of the given shape and populate it with random samples from uniform distribution
np.random.rand(3,2)

array([[ 0.58614627,  0.10336588],
       [ 0.53487062,  0.39725962],
       [ 0.86593879,  0.4330562 ]])

## array index

In [5]:
my_first_array=np.array([3,4,5,6])
print(my_first_array)

[3 4 5 6]


In [6]:
my_first_array[0]

3

In [22]:
my_first_array[3]

6

In [7]:
my_first_array[1:3]

array([4, 5])

## for a two-dim array

In [27]:
my_second_array=np.array([[3,4,5,2],[2,3,4,6],[9,5,6,1]])
print(my_second_array)

[[3 4 5 2]
 [2 3 4 6]
 [9 5 6 1]]


In [28]:
my_second_array[0]

array([3, 4, 5, 2])

In [29]:
my_second_array[2]

array([9, 5, 6, 1])

In [30]:
my_second_array[2,0]

9

In [31]:
my_second_array[2,3]

1

## array slicing: accessing subarray
## x[start:stop:step]

In [15]:
x=np.arange(11)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [16]:
print(type(x))

<class 'numpy.ndarray'>


In [17]:
x[0]

0

In [18]:
x[3]

3

In [20]:
x[1:10:2]

array([1, 3, 5, 7, 9])

In [21]:
x2=np.array( [  [3,4,5,2] , [2,3,4,6] , [9,5,6,1] ] )
print(x2)

[[3 4 5 2]
 [2 3 4 6]
 [9 5 6 1]]


In [24]:
print(x2[0:2,0:2])

[[3 4]
 [2 3]]


## create dataframe

In [6]:
import pandas as pd

In [13]:
te=np.array([[3.4,4.6,5.2],[2.1,3.2,4.9],[4.2,5.2,6.6]])
print(te)

[[ 3.4  4.6  5.2]
 [ 2.1  3.2  4.9]
 [ 4.2  5.2  6.6]]


In [14]:
df=pd.DataFrame(te,index=['aa','bb','cc'],columns=[0,1,2])

In [15]:
df

0    1    2
aa  3.4  4.6  5.2
bb  2.1  3.2  4.9
cc  4.2  5.2  6.6

In [19]:
df=pd.DataFrame(te,index=['aa','bb','cc'],columns=['A','B','C'])

In [20]:
df

A    B    C
aa  3.4  4.6  5.2
bb  2.1  3.2  4.9
cc  4.2  5.2  6.6

In [21]:
df["A"]

aa    3.4
bb    2.1
cc    4.2
Name: A, dtype: float64

In [24]:
print(type(df["A"]))

<class 'pandas.core.series.Series'>


In [22]:
df["A"]/1.5

aa    2.266667
bb    1.400000
cc    2.800000
Name: A, dtype: float64

In [25]:
x=np.ceil(df["A"]/1.5)

In [33]:
x

aa    100.0
bb      2.0
cc    100.0
Name: A, dtype: float64

In [34]:
x.where(x<3,100,inplace=False)

aa    100.0
bb      2.0
cc    100.0
Name: A, dtype: float64

In [35]:
x

aa    100.0
bb      2.0
cc    100.0
Name: A, dtype: float64