# To use Series, DataFrame,,,, import pandas 
# To use array, import numpy

In [1]:
import pandas as pd
import numpy as np

## t1 is a list
## a1 is a NumPy array

In [2]:
t1=[100,22,434,556]
a1=np.array(t1)
print(t1)
print(a1)

[100, 22, 434, 556]
[100  22 434 556]


## create a Series from list

In [3]:
data_1=pd.Series(t1)
print(data_1)

0    100
1     22
2    434
3    556
dtype: int64


## create a Series from array

In [4]:
data_2=pd.Series(a1)
print(data_1)

0    100
1     22
2    434
3    556
dtype: int64


## the index need not be an integer

In [5]:
data_3=pd.Series(t1,index=['a','b','c','d'])
print(data_3)

a    100
b     22
c    434
d    556
dtype: int64


## Creat a student grade series
## we have students : 'John','Mary', 'susan', 'Peter', 'Lin'

In [6]:
students=['John','Mary','susan','Peter','Lin']
Grade=[90,60,70,100,95]
data_4 = pd.Series(Grade,index=students)
print(data_4)
print(type(data_4))
print(data_4[0])
print(data_4[3])
print(data_4['susan'])

John      90
Mary      60
susan     70
Peter    100
Lin       95
dtype: int64
<class 'pandas.core.series.Series'>
90
100
70


## series values can be list

In [44]:
t2=[[1,2,3],[2,3,4],[4,5,6],[0,2,4.5],['go','go','never give up']]
data_5=pd.Series(t2)
print(data_5)

0                  [1, 2, 3]
1                  [2, 3, 4]
2                  [4, 5, 6]
3                [0, 2, 4.5]
4    [go, go, never give up]
dtype: object


## can we iterate a Series ? 

In [45]:
for item in t2:
    print(item)

[1, 2, 3]
[2, 3, 4]
[4, 5, 6]
[0, 2, 4.5]
['go', 'go', 'never give up']


## how to index a Series ?

In [7]:
data_4[0]

90

In [36]:
# the series value is int
print(type(data_4[0]))

<class 'numpy.int64'>


In [8]:
data_4[3]

100

In [35]:
data_4[0:2]

John    90
Mary    60
dtype: int64

In [9]:
data_4['susan']

70

## can we iterate a Series ?

In [40]:
for item in data_4:
    print(item)

90
60
70
100
95


## Create DataFrame from Series

In [10]:
students=['John','Mary','susan','Peter','Lin']
Grade=[90,60,70,100,95]
midterm_series = pd.Series(Grade,index=students)

In [11]:
hk1=['A','B','A','C','A']
hk1_series=pd.Series(hk1,students)

In [12]:
hk2=['A','A','A','B','A']
hk2_series=pd.Series(hk2,students)

In [13]:
pd1=pd.DataFrame({'Midterm':midterm_series, 'Hk1':hk1_series,
                 'HK2':hk2_series})

In [14]:
print(pd1)

      HK2 Hk1  Midterm
John    A   A       90
Mary    A   B       60
susan   A   A       70
Peter   B   C      100
Lin     A   A       95


## how to index a DataFrame?

In [17]:
# first three rows
pd1[:3]

HK2 Hk1  Midterm
John    A   A       90
Mary    A   B       60
susan   A   A       70

In [30]:
# first three rows
pd1[0:3]

HK2 Hk1  Midterm
John    A   A       90
Mary    A   B       60
susan   A   A       70

In [31]:
# take rows
pd1['John':'susan']

HK2 Hk1  Midterm
John    A   A       90
Mary    A   B       60
susan   A   A       70

In [18]:
# first two rows, two cols
pd1.iloc[:2,:2]

HK2 Hk1
John   A   A
Mary   A   B

In [32]:
# take a colum
col=pd1['Hk1']
print(col)

John     A
Mary     B
susan    A
Peter    C
Lin      A
Name: Hk1, dtype: object


In [21]:
print(type(col))

<class 'pandas.core.series.Series'>


In [33]:
# take two columns
cols=pd1[['Hk1','HK2']]
print(cols)

      Hk1 HK2
John    A   A
Mary    B   A
susan   A   A
Peter   C   B
Lin     A   A


In [27]:
print(type(cols))

<class 'pandas.core.frame.DataFrame'>


In [34]:
pd1[['Hk1']]

Hk1
John    A
Mary    B
susan   A
Peter   C
Lin     A

## Create a DataFrame from 2-D array

In [36]:
ary=np.array([ [1,2,3],[4,5,6],[7,8,9],[2,2,2],[6,6,6],[7,7,7]])
print(ary)
print(ary.shape)
print(type(ary))

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [2 2 2]
 [6 6 6]
 [7 7 7]]
(6, 3)
<class 'numpy.ndarray'>


In [40]:
df_test=pd.DataFrame(ary,columns=['col0','col1','col3'])
print(df_test)

   col0  col1  col3
0     1     2     3
1     4     5     6
2     7     8     9
3     2     2     2
4     6     6     6
5     7     7     7


## add a column

In [45]:
df_test['key1']=['A','S','B','A','A','B']

In [46]:
print(df_test)

   col0  col1  col3 key1
0     1     2     3    A
1     4     5     6    S
2     7     8     9    B
3     2     2     2    A
4     6     6     6    A
5     7     7     7    B


## GroupBy: Split, Apply,Combine

In [53]:
df_test.groupby('key1').max()

col0  col1  col3
key1                  
A        6     6     6
B        7     8     9
S        4     5     6

In [54]:
df_test.groupby('key1').sum()

col0  col1  col3
key1                  
A        9    10    11
B       14    15    16
S        4     5     6

In [49]:
print(df_test)

   col0  col1  col3 key1
0     1     2     3    A
1     4     5     6    S
2     7     8     9    B
3     2     2     2    A
4     6     6     6    A
5     7     7     7    B


In [50]:
df_test.groupby('key1')['col0'].sum()

key1
A     9
B    14
S     4
Name: col0, dtype: int64

In [51]:
print(df_test)

   col0  col1  col3 key1
0     1     2     3    A
1     4     5     6    S
2     7     8     9    B
3     2     2     2    A
4     6     6     6    A
5     7     7     7    B
